name: bangs
description: A new flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  nop:
    git:
      url: https://github.com/sersr/nop.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  plugin:
    platforms:
      android:
        package: com.example.bangs
        pluginClass: BangsPlugin
  